print("Welcome  to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
percent = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
number_of_people = int(input("How many people to split the bill? "))
tax = (total_bill * percent / 100)
pay = round((total_bill + tax) / number_of_people, 2)
print(f"Each person should pay: {pay}")